---
deployment:
  tasks:
    - export DEPLOYPATH=/home/konstantinospaph/public_html/
    - /bin/cp -R about.html $DEPLOYPATH
    - /bin/cp -R contact.html $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R resume.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
